import { defineConfig } from 'astro/config';
import react from '@astrojs/react';
import tailwind from '@astrojs/tailwind';
// Sitemap is generated by scripts/generate-sitemap.mjs (prebuild) into
// public/sitemap.xml — a single canonical file. @astrojs/sitemap is
// intentionally not used (it emits split sitemap-index.xml + sitemap-0.xml).

// NOTE: @astrojs/cloudflare adapter is omitted for pure static output.
// `output: 'static'` generates a dist/ folder deployable to Cloudflare Pages
// via `wrangler pages deploy dist/` — no adapter required.
// Add the adapter back only if you need server-side rendering (SSR) or
// Cloudflare Workers dynamic routes.

export default defineConfig({
  site: 'https://daleyorganics.com',
  output: 'static',
  trailingSlash: 'never',
  integrations: [
    react(),
    tailwind({ applyBaseStyles: false }),
  ],
  image: {
    responsiveStyles: true,
  },
});
